import { createRequire } from 'node:module';
import { writeFileSync, mkdirSync, cpSync } from 'node:fs';
import path from 'node:path';
const source=process.argv[2];
if(!source) throw new Error('Pass original source checkout');
const output='/private/tmp/iron-caravan-source-reference';
const require=createRequire(path.join(source,'package.json'));
const {build}=require('esbuild');
mkdirSync(path.join(output,'assets'),{recursive:true});
cpSync(path.join(source,'public/assets/textures'),path.join(output,'assets/textures'),{recursive:true});
const entry=String.raw`
import {createSceneInfrastructure} from './src/client/infrastructure/three/scene.ts';
import {buildWorld} from './src/client/infrastructure/three/world-builder.ts';
import {createTextureAssets} from './src/client/infrastructure/three/texture-assets.ts';
import {createCaravanViews} from './src/client/infrastructure/three/caravan-views.ts';
import {moduleSlots} from './src/client/contexts/caravan/catalog.ts';
import {moduleMountPosition} from './src/client/contexts/caravan/build-layout.ts';
import {RNG} from './src/client/core/math.ts';
const params=new URLSearchParams(location.search);
const seed=Number(params.get('seed')??72841)>>>0;
const rng=new RNG(seed);
const viewport=()=>({width:innerWidth,height:innerHeight,pixelRatio:1});
const runtime=createSceneInfrastructure({canvas:document.querySelector('canvas'),getRng:()=>rng,getViewport:viewport,onContextLost:()=>{window.__referenceError='WebGL context lost'}});
const textures=await createTextureAssets(runtime);
const world=buildWorld(runtime,textures,seed);
const views=createCaravanViews(runtime);
const crawler=views.createFortressModel(false,.88,'full',new RNG(seed));
crawler.position.set(0,.04,0);
const turret=views.createModuleVisual('assaultRifle');
const slot=moduleMountPosition({carrierId:'crawler',slot:0},moduleSlots);
turret.position.set(slot.x,slot.y,slot.z);
turret.rotation.y=slot.rotationY;
crawler.add(turret);
runtime.scene.add(crawler);
runtime.resize();
const x=Number(params.get('x')??0),z=Number(params.get('z')??5),zoom=Number(params.get('zoom')??31);
runtime.camera.position.set(x+34,45,z+34);
runtime.camera.lookAt(x,0,z);
runtime.camera.left=-zoom*innerWidth/innerHeight;
runtime.camera.right=zoom*innerWidth/innerHeight;
runtime.camera.top=zoom;
runtime.camera.bottom=-zoom;
runtime.camera.updateProjectionMatrix();
runtime.renderer.shadowMap.needsUpdate=true;
await runtime.prepareForGameplay();
for(let i=0;i<3;i++) await new Promise(requestAnimationFrame);
runtime.renderer.render(runtime.scene,runtime.camera);
window.__referenceMetadata={seed,width:innerWidth,height:innerHeight,zoom,focus:[x,0,z],roads:world.kingdomRoads.length,props:world.destructibleProps.length};
window.__referenceReady=true;
window.__referenceRuntime=runtime;
`;
await build({stdin:{contents:entry,resolveDir:source,sourcefile:'source-reference.ts',loader:'ts'},outfile:path.join(output,'assets/bundle.js'),bundle:true,platform:'browser',format:'esm',target:'es2022',logLevel:'warning'});
writeFileSync(path.join(output,'index.html'),'<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Iron Caravan source reference</title><style>html,body{margin:0;width:100%;height:100%;overflow:hidden}canvas{display:block;width:100%;height:100%}</style></head><body><canvas></canvas><script>window.__referenceReady=false;window.addEventListener("error",event=>window.__referenceError=event.message);window.addEventListener("unhandledrejection",event=>window.__referenceError=String(event.reason));</script><script type="module" src="/assets/bundle.js"></script></body></html>');
console.log(output+'/index.html');
